#!/usr/bin/env bash
# Install LiteLoaderQQNT entry into a macOS QQ.app (does NOT bypass integrity).
# Usage:
#   ./scripts/install-macos.sh [/path/to/QQ.app] [/path/to/LiteLoaderQQNT]
#
# LiteLoader root MUST be sandbox-readable, e.g.:
#   ~/Library/Containers/com.tencent.qq/Data/Documents/LiteLoaderQQNT
set -euo pipefail

QQ_APP="${1:-/Applications/QQ.app}"
LL_ROOT="${2:-$(cd "$(dirname "$0")/.." && pwd)}"

APP_DIR="$QQ_APP/Contents/Resources/app"
LAUNCHER_DIR="$APP_DIR/app_launcher"
PKG_JSON="$APP_DIR/package.json"
ML_INSTALL="$LAUNCHER_DIR/ml_install.js"

if [[ ! -d "$QQ_APP" ]]; then
  echo "QQ.app not found: $QQ_APP" >&2
  exit 1
fi
if [[ ! -f "$LL_ROOT/src/main.js" || ! -f "$LL_ROOT/package.json" ]]; then
  echo "LiteLoader root invalid: $LL_ROOT" >&2
  exit 1
fi

# Warn if root is outside QQ sandbox container (will EPERM at runtime)
case "$LL_ROOT" in
  */Library/Containers/com.tencent.qq/*) ;;
  *)
    echo "WARNING: LiteLoader root may be unreadable under QQ App Sandbox:" >&2
    echo "  $LL_ROOT" >&2
    echo "Prefer: \$HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoaderQQNT" >&2
    ;;
esac

echo "QQ:         $QQ_APP"
echo "LiteLoader: $LL_ROOT"

if [[ ! -f "$PKG_JSON.liteloader-backup" ]]; then
  cp -p "$PKG_JSON" "$PKG_JSON.liteloader-backup"
  echo "Backed up package.json -> package.json.liteloader-backup"
fi

mkdir -p "$LAUNCHER_DIR"

# Generate pinned-root shim (handles QQEX* helper processes)
PINNED=$(node -e 'console.log(JSON.stringify(process.argv[1]))' "$LL_ROOT")
cat > "$ML_INSTALL" <<EOF
/**
 * Auto-generated by scripts/install-macos.sh — LiteLoaderQQNT macOS entry
 * Handles main QQ + QQEX* helper processes (resourcesPath differs).
 */
const fs = require("fs");
const path = require("path");

const PINNED_ROOT = ${PINNED};
const STOCK_MAIN_FALLBACK = "./application.asar/app_launcher/index.js";

function isHelperProcess() {
  return String(process.resourcesPath || "").includes(path.sep + "Contents" + path.sep + "MacOS" + path.sep);
}

function mainQqApp() {
  let res = path.resolve(process.resourcesPath || "");
  const marker = path.sep + "Contents" + path.sep + "MacOS" + path.sep;
  const idx = res.indexOf(marker);
  if (idx !== -1) res = path.join(res.slice(0, idx), "Contents", "Resources");
  return path.join(res, "app");
}

function stockMainRel(qqApp) {
  try {
    const bak = path.join(qqApp, "package.json.liteloader-backup");
    if (fs.existsSync(bak)) {
      const pkg = JSON.parse(fs.readFileSync(bak, "utf-8"));
      if (pkg.main && !String(pkg.main).includes("ml_install") && !String(pkg.main).includes("LiteLoader")) {
        return pkg.main.startsWith("./") ? pkg.main : "./" + pkg.main;
      }
    }
  } catch {}
  return STOCK_MAIN_FALLBACK;
}

function requireStock(qqApp) {
  require(path.join(qqApp, stockMainRel(qqApp)));
}

const qqApp = mainQqApp();

if (isHelperProcess()) {
  // QQEXDOC / QQEXGuild / ... — do not load LiteLoader; chain host stock entry only.
  try { requireStock(qqApp); }
  catch (err) { console.error("[LiteLoader] helper stock entry failed:", err); }
} else {
  try {
    const root = process.env.LITELOADERQQNT_ROOT || PINNED_ROOT;
    const mainJs = path.join(root, "src", "main.js");
    if (!fs.existsSync(mainJs)) throw new Error("missing " + mainJs);
    process.env.LITELOADERQQNT_ROOT = root;
    require(mainJs);
  } catch (err) {
    console.error("[LiteLoader] load failed, fail-open:", err);
    try { requireStock(qqApp); }
    catch (e2) { console.error("[LiteLoader] stock entry also failed:", e2); }
  }
}
EOF

node -e '
const fs = require("fs");
const p = process.argv[1];
const j = JSON.parse(fs.readFileSync(p, "utf8"));
j.main = "./app_launcher/ml_install.js";
fs.writeFileSync(p, JSON.stringify(j, null, 2) + "\n");
console.log("package.json main ->", j.main);
' "$PKG_JSON"

echo "Done."
echo "Note: QQ file integrity bypass is still required separately."
echo "Sandbox tip: keep code under Containers/com.tencent.qq/..."
